(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={raw:{},items:[],category:'All',query:'',sort:'name',favorites:new Set(JSON.parse(localStorage.getItem('moviehub-favorites')||'[]'))};
const slug=u=>{try{return new URL(u).hostname.replace(/^www\./,'')}catch{return ''}};
const title=u=>{const h=slug(u);return h?h.split('.')[0].replace(/[-_]+/g,' ').replace(/\b\w/g,x=>x.toUpperCase()):'Catalog entry'};
const escape=s=>String(s).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
const normalize=(x,category,index)=>({category,url:String(x?.url||''),logo:String(x?.logo_url||x?.logo||''),name:String(x?.name||''),description:String(x?.description||''),tags:Array.isArray(x?.tags)?x.tags:[],index});
async function load(){
 try{
  const res=await fetch('./data.json',{cache:'no-store'});if(!res.ok)throw Error('data.json unavailable');
  state.raw=await res.json()||{};
  state.items=Object.entries(state.raw).flatMap(([category,list])=>(Array.isArray(list)?list:[]).map((x,i)=>normalize(x,category,i))).filter(x=>x.url);
  render();
 }catch(e){$('#serviceGrid').innerHTML='<div class="empty"><div>⚠</div><h3>Could not load catalog</h3><p>Make sure data.json is available beside index.html.</p></div>'}
}
function persistFavorites(){localStorage.setItem('moviehub-favorites',JSON.stringify([...state.favorites]))}
function render(){const cats=Object.entries(state.raw),total=state.items.length;$('#totalCount').textContent=total;$('#categoryCount').textContent=cats.length;$('#visibleCount').textContent=state.favorites.size;$('#progressBar').style.width=(total?100:0)+'%';renderCategories(cats);renderFilters(cats);renderServices()}
function renderCategories(cats){$('#categoryGrid').innerHTML=cats.map(([name,list])=>`<button class="category" data-category="${escape(name)}"><span class="arrow">↗</span><div class="num">${String(list?.length||0).padStart(2,'0')}</div><h3>${escape(name)}</h3><p>${list?.length||0} catalog entries</p></button>`).join('');$$('.category').forEach(c=>c.onclick=()=>{state.category=c.dataset.category;$('#directory').scrollIntoView({behavior:'smooth'});renderFilters(Object.entries(state.raw));renderServices()})}
function renderFilters(cats){$('#filters').innerHTML=['All',...cats.map(x=>x[0])].map(c=>`<button class="filter ${state.category===c?'active':''}" data-filter="${escape(c)}">${escape(c)}</button>`).join('')+`<button class="filter ${state.category==='Favorites'?'active':''}" data-filter="Favorites">♥ Favorites</button>`;$$('.filter').forEach(b=>b.onclick=()=>{state.category=b.dataset.filter;renderFilters(Object.entries(state.raw));renderServices()})}
function searchable(x){return [x.name,title(x.url),x.category,x.description,x.url,...x.tags].join(' ').toLowerCase()}
function renderServices(){const q=state.query.trim().toLowerCase();let list=state.items.filter(x=>state.category==='All'||(state.category==='Favorites'?state.favorites.has(x.url):x.category===state.category));if(q)list=list.filter(x=>searchable(x).includes(q));if(state.sort==='name')list.sort((a,b)=>(a.name||title(a.url)).localeCompare(b.name||title(b.url)));if(state.sort==='category')list.sort((a,b)=>a.category.localeCompare(b.category)||(a.name||title(a.url)).localeCompare(b.name||title(b.url)));if(state.sort==='source')list.sort((a,b)=>a.index-b.index);$('#resultCount').textContent=`${list.length} result${list.length===1?'':'s'}`;$('#serviceGrid').innerHTML=list.map(x=>{const name=x.name||title(x.url),fav=state.favorites.has(x.url),logo=x.logo?`<img src="${escape(x.logo)}" alt="${escape(name)} logo" loading="lazy" referrerpolicy="no-referrer" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'">`:'';return `<article class="service"><a class="service-link" href="${escape(x.url)}" target="_blank" rel="noopener noreferrer"><div class="service-top"><div class="service-icon has-logo">${logo}<span>${escape(name.slice(0,1).toUpperCase())}</span></div><span class="pill">${escape(x.category)}</span></div><h3>${escape(name)}</h3><p>${escape(x.description||slug(x.url))}</p>${x.tags.length?`<div class="tags">${x.tags.slice(0,3).map(t=>`<span class="tag">${escape(t)}</span>`).join('')}</div>`:''}</a><button class="favorite ${fav?'active':''}" data-favorite="${escape(x.url)}" aria-label="${fav?'Remove from':'Add to'} favorites">${fav?'♥':'♡'}</button></article>`}).join('');$('#empty').classList.toggle('hidden',list.length!==0);bindFavorites()}
function bindFavorites(){$$('[data-favorite]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const url=b.dataset.favorite;if(state.favorites.has(url))state.favorites.delete(url);else state.favorites.add(url);persistFavorites();renderServices();$('#visibleCount').textContent=state.favorites.size})}
function bind(){$('#search').oninput=e=>{state.query=e.target.value;$('#clearSearch').style.opacity=state.query?'1':'.35';renderServices()};$('#clearSearch').onclick=()=>{$('#search').value='';state.query='';$('#clearSearch').style.opacity='.35';renderServices()};$('#sort').onchange=e=>{state.sort=e.target.value;renderServices()};$$('[data-scroll]').forEach(b=>b.onclick=()=>$(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('moviehub-theme',document.body.classList.contains('light')?'light':'dark')};$('#menuBtn').onclick=()=>$('.nav-links').classList.toggle('open')}
if(localStorage.getItem('moviehub-theme')==='light')document.body.classList.add('light');
load();bind();
})();
