const DATA=window.MOVIEHUB_DATA;const $=s=>document.querySelector(s);const stats=$('#stats'),categoryGrid=$('#categoryGrid'),serviceGrid=$('#serviceGrid'),featuredGrid=$('#featuredGrid'),search=$('#search'),title=$('#serviceTitle'),count=$('#resultCount'),empty=$('#empty'),clear=$('#clearSearch'),regionSelect=$('#regionSelect'),regionFlag=$('#regionFlag'),regionLabel=$('#regionLabel'),sortSelect=$('#sortSelect'),favoriteCount=$('#favoriteCount'),modal=$('#serviceModal'),recentGrid=$('#recentGrid'),recentEmpty=$('#recentEmpty');let active='all',filter='all',region=localStorage.getItem('moviehub-region')||'global',sort=localStorage.getItem('moviehub-sort')||'featured',favorites=new Set(JSON.parse(localStorage.getItem('moviehub-favorites')||'[]')),recent=JSON.parse(localStorage.getItem('moviehub-recent')||'[]');
const regionData=()=>DATA.regions.find(r=>r.id===region)||DATA.regions[0];
function available(s){return region==='global'||s.regions.includes(region)||s.regions.includes('global')}
function categoryName(s){return DATA.categories.find(c=>c.id===s.category)?.name||'Service'}
function score(s,q){const n=s.name.toLowerCase(),d=s.desc.toLowerCase(),c=categoryName(s).toLowerCase();if(!q)return 0;if(n===q)return 100;if(n.startsWith(q))return 85;if(n.includes(q))return 70;if(c.includes(q))return 48;if(d.includes(q))return 30;return q.split(/\s+/).reduce((v,w)=>v+(n.includes(w)?16:d.includes(w)?8:c.includes(w)?6:0),0)}
function renderStats(){const visible=DATA.services.filter(available);stats.innerHTML=`<div class="stat"><strong>${visible.length}</strong><small>Services</small></div><div class="stat"><strong>${DATA.categories.filter(c=>visible.some(s=>s.category===c.id)).length}</strong><small>Categories</small></div><div class="stat"><strong>${DATA.regions.length}</strong><small>Regions</small></div>`}
function renderRegions(){regionSelect.innerHTML=DATA.regions.map(r=>`<option value="${r.id}">${r.flag} ${r.name}</option>`).join('');regionSelect.value=region;regionFlag.textContent=regionData().flag;regionLabel.textContent=`${regionData().flag} ${regionData().name}`}
function renderCategories(){categoryGrid.innerHTML=DATA.categories.map(c=>{const n=DATA.services.filter(s=>s.category===c.id&&available(s)).length;return `<article class="category ${active===c.id?'selected':''}" data-cat="${c.id}"><div class="cat-icon">${c.icon}</div><h3>${c.name}</h3><p>${n} services · ${c.desc}</p><span class="arrow">→</span></article>`}).join('');categoryGrid.querySelectorAll('.category').forEach(x=>x.onclick=()=>{active=x.dataset.cat;renderCategories();renderServices();location.hash='services';document.querySelector('#services').scrollIntoView({behavior:'smooth'})})}
function card(s,featured=false){const saved=favorites.has(s.name);return `<article class="service ${featured?'featured-service':''}" data-name="${s.name}"><button class="heart ${saved?'saved':''}" data-fav="${s.name}" aria-label="${saved?'Remove':'Save'} ${s.name}">${saved?'♥':'♡'}</button><button class="service-main" data-open="${s.name}"><span class="service-icon">${s.icon}</span><span class="service-info"><span class="service-name">${s.name}</span><span class="service-desc">${s.desc}</span></span><span class="tag">${s.tag}</span><span class="open-arrow">↗</span></button></article>`}
function renderFeatured(){const list=DATA.services.filter(s=>available(s)&&s.featured).slice(0,6);featuredGrid.innerHTML=list.map(s=>card(s,true)).join('');bindCards(featuredGrid)}
function renderRecent(){const list=recent.map(n=>DATA.services.find(s=>s.name===n)).filter(Boolean).filter(available);recentGrid.innerHTML=list.map(s=>card(s)).join('');recentEmpty.classList.toggle('hidden',list.length>0);bindCards(recentGrid)}
function addRecent(name){recent=[name,...recent.filter(n=>n!==name)].slice(0,8);localStorage.setItem('moviehub-recent',JSON.stringify(recent));renderRecent()}
function renderServices(){const q=search.value.trim().toLowerCase();let list=DATA.services.filter(s=>available(s)&&(active==='all'||s.category===active));if(filter==='free')list=list.filter(s=>s.tag==='Free'||s.tag==='Library');if(filter==='paid')list=list.filter(s=>s.tag==='Paid');if(filter==='favorites')list=list.filter(s=>favorites.has(s.name));if(q)list=list.map(s=>({...s,_score:score(s,q)})).filter(s=>s._score>0).sort((a,b)=>b._score-a._score);else if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));else if(sort==='category')list.sort((a,b)=>categoryName(a).localeCompare(categoryName(b))||a.name.localeCompare(b.name));else list.sort((a,b)=>(b.featured?1:0)-(a.featured?1:0));title.textContent=q?`Results for “${q}”`:filter==='favorites'?'Your favorites':active==='all'?'All services':categoryName({category:active});count.textContent=`${list.length} result${list.length===1?'':'s'}`;clear.classList.toggle('hidden',!q);serviceGrid.innerHTML=list.map(s=>card(s)).join('');empty.classList.toggle('hidden',list.length>0);serviceGrid.classList.toggle('no-results',!list.length);bindCards(serviceGrid);document.querySelector('#featured').classList.toggle('dimmed',!!q||active!=='all'||filter!=='all')}
function bindCards(root){root.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();toggleFavorite(b.dataset.fav)});root.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openModal(b.dataset.open))}
function toggleFavorite(name){favorites.has(name)?favorites.delete(name):favorites.add(name);localStorage.setItem('moviehub-favorites',JSON.stringify([...favorites]));updateFavoriteCount();renderFeatured();renderRecent();renderServices();if(modalService===name)updateModalFavorite()}
function updateFavoriteCount(){favoriteCount.textContent=favorites.size}
let modalService='';function openModal(name){const s=DATA.services.find(x=>x.name===name);if(!s)return;addRecent(name);modalService=name;$('#modalIcon').textContent=s.icon;$('#modalCategory').textContent=categoryName(s).toUpperCase();$('#modalName').textContent=s.name;$('#modalDesc').textContent=s.desc;$('#modalTag').textContent=s.tag;$('#modalRegions').textContent=`Available: ${s.regions.map(id=>DATA.regions.find(r=>r.id===id)?.name||id).join(', ')}`;$('#modalVisit').href=s.url;updateModalFavorite();modal.classList.remove('hidden');document.body.classList.add('modal-open')}
function updateModalFavorite(){const saved=favorites.has(modalService);$('#modalFav').textContent=saved?'♥ Saved':'♡ Save';$('#modalFav').classList.toggle('saved',saved)}
function closeModal(){modal.classList.add('hidden');document.body.classList.remove('modal-open');modalService=''}
regionSelect.addEventListener('change',()=>{region=regionSelect.value;localStorage.setItem('moviehub-region',region);active='all';filter='all';search.value='';document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));renderRegions();renderStats();renderCategories();renderFeatured();renderRecent();renderServices()});search.addEventListener('input',()=>{active='all';renderCategories();renderServices()});clear.onclick=()=>{search.value='';active='all';renderCategories();renderServices();search.focus()};sortSelect.value=sort;sortSelect.addEventListener('change',()=>{sort=sortSelect.value;localStorage.setItem('moviehub-sort',sort);renderServices()});document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderServices()});$('#favoritesBtn').onclick=()=>{filter=filter==='favorites'?'all':'favorites';document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===filter));location.hash='services';renderServices();document.querySelector('#services').scrollIntoView({behavior:'smooth'})};$('#clearHistory').onclick=()=>{recent=[];localStorage.removeItem('moviehub-recent');renderRecent()};$('#modalFav').onclick=()=>{if(modalService)toggleFavorite(modalService)};$('#modalClose').onclick=closeModal;$('#modalBackdrop').onclick=closeModal;document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==search){e.preventDefault();search.focus()}if(e.key==='Escape'){if(!modal.classList.contains('hidden'))closeModal();else if(document.activeElement===search){search.value='';renderServices();search.blur()}}});$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('moviehub-theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('moviehub-theme')==='light')document.body.classList.add('light');$('#year').textContent=new Date().getFullYear();updateFavoriteCount();renderRegions();renderStats();renderCategories();renderFeatured();renderRecent();renderServices();