const DATA=window.MOVIEHUB_DATA;const $=s=>document.querySelector(s);const stats=$('#stats'),categoryGrid=$('#categoryGrid'),serviceGrid=$('#serviceGrid'),featuredGrid=$('#featuredGrid'),search=$('#search'),title=$('#serviceTitle'),count=$('#resultCount'),empty=$('#empty'),clear=$('#clearSearch'),regionSelect=$('#regionSelect'),regionFlag=$('#regionFlag'),regionLabel=$('#regionLabel');let active='all',region=localStorage.getItem('moviehub-region')||'global';
const regionData=()=>DATA.regions.find(r=>r.id===region)||DATA.regions[0];
function available(s){return region==='global'||s.regions.includes(region)||s.regions.includes('global')}
function score(s,q){const n=s.name.toLowerCase(),d=s.desc.toLowerCase(),c=(DATA.categories.find(x=>x.id===s.category)?.name||'').toLowerCase();if(!q)return 0;if(n===q)return 100;if(n.startsWith(q))return 80;if(n.includes(q))return 65;if(c.includes(q))return 45;if(d.includes(q))return 30;return q.split(/\s+/).reduce((v,w)=>v+(n.includes(w)?15:d.includes(w)?8:c.includes(w)?6:0),0)}
function renderStats(){const visible=DATA.services.filter(available);stats.innerHTML=`<div class="stat"><strong>${visible.length}</strong><small>Services</small></div><div class="stat"><strong>${DATA.categories.filter(c=>visible.some(s=>s.category===c.id)).length}</strong><small>Categories</small></div><div class="stat"><strong>${regionData().flag}</strong><small>${regionData().name}</small></div>`}
function renderRegions(){regionSelect.innerHTML=DATA.regions.map(r=>`<option value="${r.id}">${r.flag} ${r.name}</option>`).join('');regionSelect.value=region;regionFlag.textContent=regionData().flag;regionLabel.textContent=`${regionData().flag} ${regionData().name}`}
function renderCategories(){categoryGrid.innerHTML=DATA.categories.map(c=>{const n=DATA.services.filter(s=>s.category===c.id&&available(s)).length;return `<article class="category ${active===c.id?'selected':''}" data-cat="${c.id}"><div class="cat-icon">${c.icon}</div><h3>${c.name}</h3><p>${n} services · ${c.desc}</p><span class="arrow">→</span></article>`}).join('');categoryGrid.querySelectorAll('.category').forEach(x=>x.onclick=()=>{active=x.dataset.cat;renderCategories();renderServices();document.querySelector('#services').scrollIntoView({behavior:'smooth',block:'start'})})}
function card(s,featured=false){return `<a class="service ${featured?'featured-service':''}" href="${s.url}" target="_blank" rel="noopener noreferrer"><span class="service-icon">${s.icon}</span><span class="service-info"><span class="service-name">${s.name}</span><span class="service-desc">${s.desc}</span></span><span class="tag">${s.tag}</span><span class="open-arrow">↗</span></a>`}
function renderFeatured(){const list=DATA.services.filter(s=>available(s)&&s.featured).slice(0,6);featuredGrid.innerHTML=list.map(s=>card(s,true)).join('')}
function renderServices(){const q=search.value.trim().toLowerCase();let list=DATA.services.filter(s=>available(s)&&(active==='all'||s.category===active));if(q)list=list.map(s=>({...s,_score:score(s,q)})).filter(s=>s._score>0).sort((a,b)=>b._score-a._score);title.textContent=active==='all'?(q?`Results for “${q}”`:'All services'):(DATA.categories.find(c=>c.id===active)?.name||'Services');count.textContent=`${list.length} result${list.length===1?'':'s'}`;clear.classList.toggle('hidden',!q);serviceGrid.innerHTML=list.map(s=>card(s)).join('');empty.classList.toggle('hidden',list.length>0);if(q||active!=='all')document.querySelector('#featured').classList.add('dimmed');else document.querySelector('#featured').classList.remove('dimmed')}
regionSelect.addEventListener('change',()=>{region=regionSelect.value;localStorage.setItem('moviehub-region',region);active='all';search.value='';renderRegions();renderStats();renderCategories();renderFeatured();renderServices()});search.addEventListener('input',()=>{active='all';renderServices()});clear.onclick=()=>{search.value='';active='all';renderCategories();renderServices();search.focus()};document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==search){e.preventDefault();search.focus()}if(e.key==='Escape'&&document.activeElement===search){search.value='';renderServices();search.blur()}});$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('moviehub-theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('moviehub-theme')==='light')document.body.classList.add('light');$('#year').textContent=new Date().getFullYear();renderRegions();renderStats();renderCategories();renderFeatured();renderServices();