window.MOVIEHUB_DATA={categories:[{id:'movies',name:'Movies & Shows',icon:'🎬',desc:'Films, TV and originals'},{id:'anime',name:'Anime',icon:'🍥',desc:'Official anime platforms'},{id:'livetv',name:'Live TV & Sports',icon:'📺',desc:'Authorized live channels'},{id:'free',name:'Free & Ad-Supported',icon:'✨',desc:'Free legal entertainment'},{id:'paid',name:'Paid Services',icon:'💳',desc:'Subscription platforms'},{id:'apps',name:'Apps & Platforms',icon:'📱',desc:'Official apps and services'}],services:[
{name:'Netflix',category:'movies',url:'https://www.netflix.com/',desc:'Movies, TV and originals',tag:'Official',icon:'N'},
{name:'Prime Video',category:'movies',url:'https://www.primevideo.com/',desc:'Movies, series and originals',tag:'Official',icon:'P'},
{name:'Disney+',category:'movies',url:'https://www.disneyplus.com/',desc:'Disney, Pixar, Marvel and more',tag:'Official',icon:'D'},
{name:'Apple TV+',category:'movies',url:'https://tv.apple.com/',desc:'Apple Originals',tag:'Official',icon:'A'},
{name:'Paramount+',category:'movies',url:'https://www.paramountplus.com/',desc:'Movies and entertainment',tag:'Official',icon:'P'},
{name:'Crunchyroll',category:'anime',url:'https://www.crunchyroll.com/',desc:'Anime streaming platform',tag:'Official',icon:'C'},
{name:'HIDIVE',category:'anime',url:'https://www.hidive.com/',desc:'Anime streaming service',tag:'Official',icon:'H'},
{name:'Pluto TV',category:'livetv',url:'https://pluto.tv/',desc:'Free live channels and on-demand',tag:'Free',icon:'P'},
{name:'Tubi',category:'free',url:'https://tubitv.com/',desc:'Free movies and TV',tag:'Free',icon:'T'},
{name:'Plex',category:'free',url:'https://www.plex.tv/',desc:'Free movies, TV and live channels',tag:'Free',icon:'P'},
{name:'The Roku Channel',category:'free',url:'https://www.roku.com/whats-on/the-roku-channel',desc:'Free and premium entertainment',tag:'Free',icon:'R'},
{name:'YouTube',category:'apps',url:'https://www.youtube.com/',desc:'Official video platform',tag:'Official',icon:'Y'},
{name:'Twitch',category:'apps',url:'https://www.twitch.tv/',desc:'Live streams and communities',tag:'Official',icon:'T'},
{name:'Fubo',category:'livetv',url:'https://www.fubo.tv/',desc:'Live TV and sports',tag:'Paid',icon:'F'},
{name:'Hulu',category:'paid',url:'https://www.hulu.com/',desc:'TV, movies and originals',tag:'Paid',icon:'H'},
{name:'Max',category:'paid',url:'https://www.max.com/',desc:'HBO and Warner Bros. entertainment',tag:'Paid',icon:'M'},
{name:'Peacock',category:'paid',url:'https://www.peacocktv.com/',desc:'Movies, shows and live events',tag:'Paid',icon:'P'},
{name:'MUBI',category:'paid',url:'https://mubi.com/',desc:'Curated cinema',tag:'Paid',icon:'M'},
{name:'Kanopy',category:'free',url:'https://www.kanopy.com/',desc:'Films through participating libraries',tag:'Library',icon:'K'},
{name:'Hoopla',category:'free',url:'https://www.hoopladigital.com/',desc:'Movies and TV through libraries',tag:'Library',icon:'H'}]};
