window.MOVIEHUB_DATA={regions:[{id:'global',name:'Global',flag:'🌎'},{id:'nepal',name:'Nepal',flag:'🇳🇵'},{id:'india',name:'India',flag:'🇮🇳'},{id:'usa',name:'United States',flag:'🇺🇸'},{id:'uk',name:'United Kingdom',flag:'🇬🇧'},{id:'kuwait',name:'Kuwait',flag:'🇰🇼'}],categories:[{id:'movies',name:'Movies & Shows',icon:'🎬',desc:'Films, TV and originals'},{id:'anime',name:'Anime',icon:'🍥',desc:'Official anime platforms'},{id:'livetv',name:'Live TV & Sports',icon:'📺',desc:'Authorized live channels'},{id:'free',name:'Free & Ad-Supported',icon:'✨',desc:'Free legal entertainment'},{id:'paid',name:'Paid Services',icon:'💳',desc:'Subscription platforms'},{id:'apps',name:'Apps & Platforms',icon:'📱',desc:'Official apps and services'}],services:[
{name:'Netflix',category:'movies',url:'https://www.netflix.com/',desc:'Movies, TV and originals',tag:'Official',icon:'N',regions:['global','nepal','india','usa','uk','kuwait'],featured:true},
{name:'Prime Video',category:'movies',url:'https://www.primevideo.com/',desc:'Movies, series and originals',tag:'Official',icon:'P',regions:['global','nepal','india','usa','uk','kuwait'],featured:true},
{name:'Disney+',category:'movies',url:'https://www.disneyplus.com/',desc:'Disney, Pixar, Marvel and more',tag:'Official',icon:'D',regions:['global','usa','uk','india','kuwait'],featured:true},
{name:'Apple TV+',category:'movies',url:'https://tv.apple.com/',desc:'Apple Originals',tag:'Official',icon:'A',regions:['global','nepal','india','usa','uk','kuwait']},
{name:'Paramount+',category:'movies',url:'https://www.paramountplus.com/',desc:'Movies and entertainment',tag:'Official',icon:'P',regions:['usa','uk']},
{name:'Crunchyroll',category:'anime',url:'https://www.crunchyroll.com/',desc:'Anime streaming platform',tag:'Official',icon:'C',regions:['global','nepal','india','usa','uk','kuwait'],featured:true},
{name:'HIDIVE',category:'anime',url:'https://www.hidive.com/',desc:'Anime streaming service',tag:'Official',icon:'H',regions:['usa','uk']},
{name:'Pluto TV',category:'livetv',url:'https://pluto.tv/',desc:'Free live channels and on-demand',tag:'Free',icon:'P',regions:['usa','uk']},
{name:'Tubi',category:'free',url:'https://tubitv.com/',desc:'Free movies and TV',tag:'Free',icon:'T',regions:['usa','uk']},
{name:'Plex',category:'free',url:'https://www.plex.tv/',desc:'Free movies, TV and live channels',tag:'Free',icon:'P',regions:['global','nepal','india','usa','uk','kuwait']},
{name:'The Roku Channel',category:'free',url:'https://www.roku.com/whats-on/the-roku-channel',desc:'Free and premium entertainment',tag:'Free',icon:'R',regions:['usa','uk']},
{name:'YouTube',category:'apps',url:'https://www.youtube.com/',desc:'Official video platform',tag:'Official',icon:'Y',regions:['global','nepal','india','usa','uk','kuwait'],featured:true},
{name:'Twitch',category:'apps',url:'https://www.twitch.tv/',desc:'Live streams and communities',tag:'Official',icon:'T',regions:['global','nepal','india','usa','uk','kuwait']},
{name:'Fubo',category:'livetv',url:'https://www.fubo.tv/',desc:'Live TV and sports',tag:'Paid',icon:'F',regions:['usa','uk']},
{name:'Hulu',category:'paid',url:'https://www.hulu.com/',desc:'TV, movies and originals',tag:'Paid',icon:'H',regions:['usa']},
{name:'Max',category:'paid',url:'https://www.max.com/',desc:'HBO and Warner Bros. entertainment',tag:'Paid',icon:'M',regions:['usa','uk']},
{name:'Peacock',category:'paid',url:'https://www.peacocktv.com/',desc:'Movies, shows and live events',tag:'Paid',icon:'P',regions:['usa']},
{name:'MUBI',category:'paid',url:'https://mubi.com/',desc:'Curated cinema',tag:'Paid',icon:'M',regions:['global','nepal','india','usa','uk','kuwait']},
{name:'Kanopy',category:'free',url:'https://www.kanopy.com/',desc:'Films through participating libraries',tag:'Library',icon:'K',regions:['usa','uk']},
{name:'Hoopla',category:'free',url:'https://www.hoopladigital.com/',desc:'Movies and TV through libraries',tag:'Library',icon:'H',regions:['usa']} ]};